name: Run Tests and Audit on PR

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  test-and-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run Unit Tests
        run: npm run ci:test

      - name: Check Unit Test Results
        run: |
          if [ $? -ne 0 ]; then
            echo "Unit tests failed. Commit rejected."
            exit 1
          fi

      - name: Run npm audit
        run: npm audit --json > audit_results.json || true

      - name: Check for Vulnerabilities
        run: |
          vulnerabilities=$(< audit_results.json)
          echo "Full audit results:"
          echo "$vulnerabilities"
          if [ "$(jq '.metadata.vulnerabilities.total' audit_results.json)" -eq 0 ]; then
            echo "No vulnerabilities found."
          else
            echo "Vulnerabilities found. Failing the check."
            exit 1
          fi
